version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: scape
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  node-api:
    build: ./node-api
    ports: ["3000:3000"]
    depends_on: [db, python-service]
    environment:
      DATABASE_URL: ${DATABASE_URL}

  python-service:
    build: ./python-service
    ports: ["8000:8000"]
    depends_on: [redis]
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}

  worker:
    build: ./python-service
    command: celery -A app.worker worker --loglevel=info
    depends_on: [redis]

volumes:
  pgdata:
